# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate from mirror

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: 'git clone https://gitlab.com/banana-hackers/store-db.git'
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - uses: actions/checkout@v2
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - name: Setup Node.js
      uses: actions:setup-node@v2.1.2
      with:
        node-version: '12.x'
    - uses: ./.github/actions/generator
