name: Generate from mirror

on:
#  schedule:
#    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        run: 'git clone https://gitlab.com/banana-hackers/store-db.git $GITHUB_WORKSPACE/store-db'
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: clone
    steps:
    - uses: actions/checkout@v2
    - name: Cache Node.js modules
      uses: actions/cache@v2
      with:
        path: ~/node_modules
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
    - uses: ./.github/actions/generator
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v2
    - run: |
        git config --global user.email "hapu@riseup.net"
        git config --global user.name "Farooq Karimi Zadeh"
        git add .
        git commit -m "generate"
        git push
