name: Generate from mirror

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  buildndeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone
        run: |
          git clone https://gitlab.com/banana-hackers/store-db.git $GITHUB_WORKSPACE/store-db
          cd $GITHUB_WORKSPACE/store-db
          git log -1 --date-order --format=format:'%ct' > last_commit_time.txt
      - name: Debugging
        run: |
          echo No debugging... moo moo
      - name: Generate
        uses: ./.github/actions/generator
      - name: Deploy
        run: |
          cd $GITHUB_WORKSPACE
          git config --global user.email "hapu@riseup.net"
          git config --global user.name "Farooq Karimi Zadeh (Actions)"
          git add .
          git commit -m "generate" && git push
          true
