name: Generate from mirror

on:
#  schedule:
#    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  buildndeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clone
        run: 'git clone https://gitlab.com/banana-hackers/store-db.git $GITHUB_WORKSPACE/store-db'
      - name: Debugging
        run: |
          ls
          ls store-db
          echo $GITHUB_WORKSPACE
          echo $PWD
      - name: Generate
        uses: ./.github/actions/generator
      - name: Deploy
        run: |
          git config --global user.email "hapu@riseup.net"
          git config --global user.name "Farooq Karimi Zadeh (Actions)"
          git add .
          git commit -m "generate"
          git push
